name: Spotifyish CI

on:
  push:
    branches:
      - develop
      - main
      - 'feature/**'
      - 'bug/**'
      - 'task/**'
  pull_request:
    branches:
      - develop
      - main
      - 'feature/**'
      - 'bug/**'
      - 'task/**'
      
jobs:
  build:
    name: Build 
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
        
    - name: Check-out code
      uses: actions/checkout@v3

    - name: Build with xcodebuild
      working-directory: ./Spotifyish
      run: |
        xcodebuild clean build \
          -scheme "Spotifyish" \
          -destination "platform=iOS Simulator,name=iPhone 16,OS=18.2" \
          -skipPackagePluginValidation \
          -skipMacroValidation \
          -derivedDataPath ./DerivedData

  test:
    name: Run Tests
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
    - name: Check-out code
      uses: actions/checkout@v3

    - name: Run tests
      working-directory: ./Spotifyish
      run: |
        xcodebuild test \
          -scheme "Spotifyish" \
          -skipPackagePluginValidation \
          -skipMacroValidation \
          -destination "platform=iOS Simulator,name=iPhone 16,OS=18.2" \
          -derivedDataPath ./DerivedData
