name: Spotifyish CI

on:
  push:
    branches:
      - develop
      - main
      - 'feature/**'
      - 'bug/**'
      - 'task/**'
  pull_request:
    branches:
      - develop
      - main
      - 'feature/**'
      - 'bug/**'
      - 'task/**'
      
jobs:
  build:
    name: Build 
    runs-on: macos-latest
    working-directory: ./Spotifyish
    steps:
      - name: Check-out code
        uses: actions/checkout@v3

      - name: Build with xcodebuild
        run: |
          xcodebuild clean build \
            -scheme "Spotifyish" \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=18.2" \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            -derivedDataPath ./DerivedData

  test:
    name: Run Tests
    runs-on: macos-latest
    working-directory: ./Spotifyish
    steps:
      - name: Check-out code
        uses: actions/checkout@v3

      - name: Run xcode tests
        run: |
          xcodebuild test \
            -scheme "Spotifyish" \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=18.2" \
            -derivedDataPath ./DerivedData
